-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity spmm_hls_set_tile_broadcast is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem1_AWVALID : OUT STD_LOGIC;
    m_axi_gmem1_AWREADY : IN STD_LOGIC;
    m_axi_gmem1_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem1_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem1_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_WVALID : OUT STD_LOGIC;
    m_axi_gmem1_WREADY : IN STD_LOGIC;
    m_axi_gmem1_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem1_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_WLAST : OUT STD_LOGIC;
    m_axi_gmem1_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_ARVALID : OUT STD_LOGIC;
    m_axi_gmem1_ARREADY : IN STD_LOGIC;
    m_axi_gmem1_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem1_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem1_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_RVALID : IN STD_LOGIC;
    m_axi_gmem1_RREADY : OUT STD_LOGIC;
    m_axi_gmem1_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem1_RLAST : IN STD_LOGIC;
    m_axi_gmem1_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_gmem1_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_BVALID : IN STD_LOGIC;
    m_axi_gmem1_BREADY : OUT STD_LOGIC;
    m_axi_gmem1_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    col_idx : IN STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem2_AWVALID : OUT STD_LOGIC;
    m_axi_gmem2_AWREADY : IN STD_LOGIC;
    m_axi_gmem2_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem2_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem2_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem2_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem2_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_WVALID : OUT STD_LOGIC;
    m_axi_gmem2_WREADY : IN STD_LOGIC;
    m_axi_gmem2_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem2_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_WLAST : OUT STD_LOGIC;
    m_axi_gmem2_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_ARVALID : OUT STD_LOGIC;
    m_axi_gmem2_ARREADY : IN STD_LOGIC;
    m_axi_gmem2_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem2_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem2_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem2_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem2_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_RVALID : IN STD_LOGIC;
    m_axi_gmem2_RREADY : OUT STD_LOGIC;
    m_axi_gmem2_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem2_RLAST : IN STD_LOGIC;
    m_axi_gmem2_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_gmem2_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_BVALID : IN STD_LOGIC;
    m_axi_gmem2_BREADY : OUT STD_LOGIC;
    m_axi_gmem2_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    a_val : IN STD_LOGIC_VECTOR (63 downto 0);
    s_0_din : OUT STD_LOGIC_VECTOR (387 downto 0);
    s_0_full_n : IN STD_LOGIC;
    s_0_write : OUT STD_LOGIC;
    s_1_din : OUT STD_LOGIC_VECTOR (387 downto 0);
    s_1_full_n : IN STD_LOGIC;
    s_1_write : OUT STD_LOGIC;
    s_2_din : OUT STD_LOGIC_VECTOR (387 downto 0);
    s_2_full_n : IN STD_LOGIC;
    s_2_write : OUT STD_LOGIC;
    s_3_din : OUT STD_LOGIC_VECTOR (387 downto 0);
    s_3_full_n : IN STD_LOGIC;
    s_3_write : OUT STD_LOGIC;
    pointer : IN STD_LOGIC_VECTOR (31 downto 0);
    nnz : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of spmm_hls_set_tile_broadcast is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal s_0_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal s_1_blk_n : STD_LOGIC;
    signal s_2_blk_n : STD_LOGIC;
    signal s_3_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_set_tile_broadcast_Pipeline_init_seen_fu_170_ap_start : STD_LOGIC;
    signal grp_set_tile_broadcast_Pipeline_init_seen_fu_170_ap_done : STD_LOGIC;
    signal grp_set_tile_broadcast_Pipeline_init_seen_fu_170_ap_idle : STD_LOGIC;
    signal grp_set_tile_broadcast_Pipeline_init_seen_fu_170_ap_ready : STD_LOGIC;
    signal grp_set_tile_broadcast_Pipeline_init_seen_fu_170_seen_v_3_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_set_tile_broadcast_Pipeline_init_seen_fu_170_seen_v_3_out_ap_vld : STD_LOGIC;
    signal grp_set_tile_broadcast_Pipeline_init_seen_fu_170_seen_v_2_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_set_tile_broadcast_Pipeline_init_seen_fu_170_seen_v_2_out_ap_vld : STD_LOGIC;
    signal grp_set_tile_broadcast_Pipeline_init_seen_fu_170_seen_v_1_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_set_tile_broadcast_Pipeline_init_seen_fu_170_seen_v_1_out_ap_vld : STD_LOGIC;
    signal grp_set_tile_broadcast_Pipeline_init_seen_fu_170_seen_v_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_set_tile_broadcast_Pipeline_init_seen_fu_170_seen_v_out_ap_vld : STD_LOGIC;
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_ap_start : STD_LOGIC;
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_ap_done : STD_LOGIC;
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_ap_idle : STD_LOGIC;
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_ap_ready : STD_LOGIC;
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_AWVALID : STD_LOGIC;
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_WVALID : STD_LOGIC;
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_WDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_WSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_WLAST : STD_LOGIC;
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_ARVALID : STD_LOGIC;
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_RREADY : STD_LOGIC;
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_BREADY : STD_LOGIC;
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_AWVALID : STD_LOGIC;
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_WVALID : STD_LOGIC;
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_WDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_WSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_WLAST : STD_LOGIC;
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_ARVALID : STD_LOGIC;
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_RREADY : STD_LOGIC;
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_BREADY : STD_LOGIC;
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_pkt_ref_3_088_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_pkt_ref_3_088_out_ap_vld : STD_LOGIC;
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_pkt_ref_2_087_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_pkt_ref_2_087_out_ap_vld : STD_LOGIC;
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_pkt_ref_1_086_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_pkt_ref_1_086_out_ap_vld : STD_LOGIC;
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_pkt_ref_0_085_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_pkt_ref_0_085_out_ap_vld : STD_LOGIC;
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_pkt_v_y_3_084_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_pkt_v_y_3_084_out_ap_vld : STD_LOGIC;
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_pkt_v_y_2_083_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_pkt_v_y_2_083_out_ap_vld : STD_LOGIC;
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_pkt_v_y_1_082_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_pkt_v_y_1_082_out_ap_vld : STD_LOGIC;
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_pkt_v_y_0_081_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_pkt_v_y_0_081_out_ap_vld : STD_LOGIC;
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_pkt_v_value_3_080_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_pkt_v_value_3_080_out_ap_vld : STD_LOGIC;
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_pkt_v_value_2_079_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_pkt_v_value_2_079_out_ap_vld : STD_LOGIC;
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_pkt_v_value_1_078_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_pkt_v_value_1_078_out_ap_vld : STD_LOGIC;
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_pkt_v_value_0_077_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_pkt_v_value_0_077_out_ap_vld : STD_LOGIC;
    signal grp_set_tile_broadcast_Pipeline_init_seen_fu_170_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal p_0_fu_278_p17 : STD_LOGIC_VECTOR (387 downto 0);
    signal ap_block_state5 : BOOLEAN;
    signal bitcast_ln96_3_fu_274_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln96_2_fu_270_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln96_1_fu_266_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln96_fu_262_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component spmm_hls_set_tile_broadcast_Pipeline_init_seen IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        seen_v_3_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        seen_v_3_out_ap_vld : OUT STD_LOGIC;
        seen_v_2_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        seen_v_2_out_ap_vld : OUT STD_LOGIC;
        seen_v_1_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        seen_v_1_out_ap_vld : OUT STD_LOGIC;
        seen_v_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        seen_v_out_ap_vld : OUT STD_LOGIC );
    end component;


    component spmm_hls_set_tile_broadcast_Pipeline_copy_tile_loop IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        m_axi_gmem2_AWVALID : OUT STD_LOGIC;
        m_axi_gmem2_AWREADY : IN STD_LOGIC;
        m_axi_gmem2_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem2_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem2_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem2_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem2_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem2_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem2_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem2_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem2_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem2_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem2_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem2_WVALID : OUT STD_LOGIC;
        m_axi_gmem2_WREADY : IN STD_LOGIC;
        m_axi_gmem2_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem2_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem2_WLAST : OUT STD_LOGIC;
        m_axi_gmem2_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem2_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem2_ARVALID : OUT STD_LOGIC;
        m_axi_gmem2_ARREADY : IN STD_LOGIC;
        m_axi_gmem2_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem2_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem2_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem2_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem2_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem2_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem2_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem2_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem2_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem2_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem2_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem2_RVALID : IN STD_LOGIC;
        m_axi_gmem2_RREADY : OUT STD_LOGIC;
        m_axi_gmem2_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem2_RLAST : IN STD_LOGIC;
        m_axi_gmem2_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem2_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
        m_axi_gmem2_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem2_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem2_BVALID : IN STD_LOGIC;
        m_axi_gmem2_BREADY : OUT STD_LOGIC;
        m_axi_gmem2_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem2_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem2_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_AWVALID : OUT STD_LOGIC;
        m_axi_gmem1_AWREADY : IN STD_LOGIC;
        m_axi_gmem1_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem1_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem1_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem1_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem1_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_WVALID : OUT STD_LOGIC;
        m_axi_gmem1_WREADY : IN STD_LOGIC;
        m_axi_gmem1_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem1_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_WLAST : OUT STD_LOGIC;
        m_axi_gmem1_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_ARVALID : OUT STD_LOGIC;
        m_axi_gmem1_ARREADY : IN STD_LOGIC;
        m_axi_gmem1_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem1_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem1_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem1_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem1_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_RVALID : IN STD_LOGIC;
        m_axi_gmem1_RREADY : OUT STD_LOGIC;
        m_axi_gmem1_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem1_RLAST : IN STD_LOGIC;
        m_axi_gmem1_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
        m_axi_gmem1_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_BVALID : IN STD_LOGIC;
        m_axi_gmem1_BREADY : OUT STD_LOGIC;
        m_axi_gmem1_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        seen_v_3_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        seen_v_2_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        seen_v_1_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        seen_v_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        pointer : IN STD_LOGIC_VECTOR (31 downto 0);
        nnz : IN STD_LOGIC_VECTOR (31 downto 0);
        a_val : IN STD_LOGIC_VECTOR (63 downto 0);
        col_idx : IN STD_LOGIC_VECTOR (63 downto 0);
        pkt_ref_3_088_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        pkt_ref_3_088_out_ap_vld : OUT STD_LOGIC;
        pkt_ref_2_087_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        pkt_ref_2_087_out_ap_vld : OUT STD_LOGIC;
        pkt_ref_1_086_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        pkt_ref_1_086_out_ap_vld : OUT STD_LOGIC;
        pkt_ref_0_085_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        pkt_ref_0_085_out_ap_vld : OUT STD_LOGIC;
        pkt_v_y_3_084_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        pkt_v_y_3_084_out_ap_vld : OUT STD_LOGIC;
        pkt_v_y_2_083_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        pkt_v_y_2_083_out_ap_vld : OUT STD_LOGIC;
        pkt_v_y_1_082_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        pkt_v_y_1_082_out_ap_vld : OUT STD_LOGIC;
        pkt_v_y_0_081_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        pkt_v_y_0_081_out_ap_vld : OUT STD_LOGIC;
        pkt_v_value_3_080_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        pkt_v_value_3_080_out_ap_vld : OUT STD_LOGIC;
        pkt_v_value_2_079_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        pkt_v_value_2_079_out_ap_vld : OUT STD_LOGIC;
        pkt_v_value_1_078_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        pkt_v_value_1_078_out_ap_vld : OUT STD_LOGIC;
        pkt_v_value_0_077_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        pkt_v_value_0_077_out_ap_vld : OUT STD_LOGIC );
    end component;



begin
    grp_set_tile_broadcast_Pipeline_init_seen_fu_170 : component spmm_hls_set_tile_broadcast_Pipeline_init_seen
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_set_tile_broadcast_Pipeline_init_seen_fu_170_ap_start,
        ap_done => grp_set_tile_broadcast_Pipeline_init_seen_fu_170_ap_done,
        ap_idle => grp_set_tile_broadcast_Pipeline_init_seen_fu_170_ap_idle,
        ap_ready => grp_set_tile_broadcast_Pipeline_init_seen_fu_170_ap_ready,
        seen_v_3_out => grp_set_tile_broadcast_Pipeline_init_seen_fu_170_seen_v_3_out,
        seen_v_3_out_ap_vld => grp_set_tile_broadcast_Pipeline_init_seen_fu_170_seen_v_3_out_ap_vld,
        seen_v_2_out => grp_set_tile_broadcast_Pipeline_init_seen_fu_170_seen_v_2_out,
        seen_v_2_out_ap_vld => grp_set_tile_broadcast_Pipeline_init_seen_fu_170_seen_v_2_out_ap_vld,
        seen_v_1_out => grp_set_tile_broadcast_Pipeline_init_seen_fu_170_seen_v_1_out,
        seen_v_1_out_ap_vld => grp_set_tile_broadcast_Pipeline_init_seen_fu_170_seen_v_1_out_ap_vld,
        seen_v_out => grp_set_tile_broadcast_Pipeline_init_seen_fu_170_seen_v_out,
        seen_v_out_ap_vld => grp_set_tile_broadcast_Pipeline_init_seen_fu_170_seen_v_out_ap_vld);

    grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178 : component spmm_hls_set_tile_broadcast_Pipeline_copy_tile_loop
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_ap_start,
        ap_done => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_ap_done,
        ap_idle => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_ap_idle,
        ap_ready => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_ap_ready,
        m_axi_gmem2_AWVALID => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_AWVALID,
        m_axi_gmem2_AWREADY => ap_const_logic_0,
        m_axi_gmem2_AWADDR => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_AWADDR,
        m_axi_gmem2_AWID => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_AWID,
        m_axi_gmem2_AWLEN => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_AWLEN,
        m_axi_gmem2_AWSIZE => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_AWSIZE,
        m_axi_gmem2_AWBURST => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_AWBURST,
        m_axi_gmem2_AWLOCK => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_AWLOCK,
        m_axi_gmem2_AWCACHE => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_AWCACHE,
        m_axi_gmem2_AWPROT => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_AWPROT,
        m_axi_gmem2_AWQOS => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_AWQOS,
        m_axi_gmem2_AWREGION => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_AWREGION,
        m_axi_gmem2_AWUSER => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_AWUSER,
        m_axi_gmem2_WVALID => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_WVALID,
        m_axi_gmem2_WREADY => ap_const_logic_0,
        m_axi_gmem2_WDATA => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_WDATA,
        m_axi_gmem2_WSTRB => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_WSTRB,
        m_axi_gmem2_WLAST => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_WLAST,
        m_axi_gmem2_WID => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_WID,
        m_axi_gmem2_WUSER => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_WUSER,
        m_axi_gmem2_ARVALID => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_ARVALID,
        m_axi_gmem2_ARREADY => m_axi_gmem2_ARREADY,
        m_axi_gmem2_ARADDR => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_ARADDR,
        m_axi_gmem2_ARID => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_ARID,
        m_axi_gmem2_ARLEN => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_ARLEN,
        m_axi_gmem2_ARSIZE => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_ARSIZE,
        m_axi_gmem2_ARBURST => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_ARBURST,
        m_axi_gmem2_ARLOCK => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_ARLOCK,
        m_axi_gmem2_ARCACHE => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_ARCACHE,
        m_axi_gmem2_ARPROT => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_ARPROT,
        m_axi_gmem2_ARQOS => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_ARQOS,
        m_axi_gmem2_ARREGION => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_ARREGION,
        m_axi_gmem2_ARUSER => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_ARUSER,
        m_axi_gmem2_RVALID => m_axi_gmem2_RVALID,
        m_axi_gmem2_RREADY => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_RREADY,
        m_axi_gmem2_RDATA => m_axi_gmem2_RDATA,
        m_axi_gmem2_RLAST => m_axi_gmem2_RLAST,
        m_axi_gmem2_RID => m_axi_gmem2_RID,
        m_axi_gmem2_RFIFONUM => m_axi_gmem2_RFIFONUM,
        m_axi_gmem2_RUSER => m_axi_gmem2_RUSER,
        m_axi_gmem2_RRESP => m_axi_gmem2_RRESP,
        m_axi_gmem2_BVALID => ap_const_logic_0,
        m_axi_gmem2_BREADY => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_BREADY,
        m_axi_gmem2_BRESP => ap_const_lv2_0,
        m_axi_gmem2_BID => ap_const_lv1_0,
        m_axi_gmem2_BUSER => ap_const_lv1_0,
        m_axi_gmem1_AWVALID => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_AWVALID,
        m_axi_gmem1_AWREADY => ap_const_logic_0,
        m_axi_gmem1_AWADDR => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_AWADDR,
        m_axi_gmem1_AWID => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_AWID,
        m_axi_gmem1_AWLEN => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_AWLEN,
        m_axi_gmem1_AWSIZE => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_AWSIZE,
        m_axi_gmem1_AWBURST => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_AWBURST,
        m_axi_gmem1_AWLOCK => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_AWLOCK,
        m_axi_gmem1_AWCACHE => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_AWCACHE,
        m_axi_gmem1_AWPROT => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_AWPROT,
        m_axi_gmem1_AWQOS => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_AWQOS,
        m_axi_gmem1_AWREGION => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_AWREGION,
        m_axi_gmem1_AWUSER => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_AWUSER,
        m_axi_gmem1_WVALID => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_WVALID,
        m_axi_gmem1_WREADY => ap_const_logic_0,
        m_axi_gmem1_WDATA => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_WDATA,
        m_axi_gmem1_WSTRB => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_WSTRB,
        m_axi_gmem1_WLAST => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_WLAST,
        m_axi_gmem1_WID => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_WID,
        m_axi_gmem1_WUSER => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_WUSER,
        m_axi_gmem1_ARVALID => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_ARVALID,
        m_axi_gmem1_ARREADY => m_axi_gmem1_ARREADY,
        m_axi_gmem1_ARADDR => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_ARADDR,
        m_axi_gmem1_ARID => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_ARID,
        m_axi_gmem1_ARLEN => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_ARLEN,
        m_axi_gmem1_ARSIZE => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_ARSIZE,
        m_axi_gmem1_ARBURST => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_ARBURST,
        m_axi_gmem1_ARLOCK => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_ARLOCK,
        m_axi_gmem1_ARCACHE => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_ARCACHE,
        m_axi_gmem1_ARPROT => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_ARPROT,
        m_axi_gmem1_ARQOS => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_ARQOS,
        m_axi_gmem1_ARREGION => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_ARREGION,
        m_axi_gmem1_ARUSER => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_ARUSER,
        m_axi_gmem1_RVALID => m_axi_gmem1_RVALID,
        m_axi_gmem1_RREADY => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_RREADY,
        m_axi_gmem1_RDATA => m_axi_gmem1_RDATA,
        m_axi_gmem1_RLAST => m_axi_gmem1_RLAST,
        m_axi_gmem1_RID => m_axi_gmem1_RID,
        m_axi_gmem1_RFIFONUM => m_axi_gmem1_RFIFONUM,
        m_axi_gmem1_RUSER => m_axi_gmem1_RUSER,
        m_axi_gmem1_RRESP => m_axi_gmem1_RRESP,
        m_axi_gmem1_BVALID => ap_const_logic_0,
        m_axi_gmem1_BREADY => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_BREADY,
        m_axi_gmem1_BRESP => ap_const_lv2_0,
        m_axi_gmem1_BID => ap_const_lv1_0,
        m_axi_gmem1_BUSER => ap_const_lv1_0,
        seen_v_3_reload => grp_set_tile_broadcast_Pipeline_init_seen_fu_170_seen_v_3_out,
        seen_v_2_reload => grp_set_tile_broadcast_Pipeline_init_seen_fu_170_seen_v_2_out,
        seen_v_1_reload => grp_set_tile_broadcast_Pipeline_init_seen_fu_170_seen_v_1_out,
        seen_v_reload => grp_set_tile_broadcast_Pipeline_init_seen_fu_170_seen_v_out,
        pointer => pointer,
        nnz => nnz,
        a_val => a_val,
        col_idx => col_idx,
        pkt_ref_3_088_out => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_pkt_ref_3_088_out,
        pkt_ref_3_088_out_ap_vld => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_pkt_ref_3_088_out_ap_vld,
        pkt_ref_2_087_out => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_pkt_ref_2_087_out,
        pkt_ref_2_087_out_ap_vld => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_pkt_ref_2_087_out_ap_vld,
        pkt_ref_1_086_out => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_pkt_ref_1_086_out,
        pkt_ref_1_086_out_ap_vld => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_pkt_ref_1_086_out_ap_vld,
        pkt_ref_0_085_out => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_pkt_ref_0_085_out,
        pkt_ref_0_085_out_ap_vld => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_pkt_ref_0_085_out_ap_vld,
        pkt_v_y_3_084_out => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_pkt_v_y_3_084_out,
        pkt_v_y_3_084_out_ap_vld => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_pkt_v_y_3_084_out_ap_vld,
        pkt_v_y_2_083_out => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_pkt_v_y_2_083_out,
        pkt_v_y_2_083_out_ap_vld => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_pkt_v_y_2_083_out_ap_vld,
        pkt_v_y_1_082_out => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_pkt_v_y_1_082_out,
        pkt_v_y_1_082_out_ap_vld => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_pkt_v_y_1_082_out_ap_vld,
        pkt_v_y_0_081_out => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_pkt_v_y_0_081_out,
        pkt_v_y_0_081_out_ap_vld => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_pkt_v_y_0_081_out_ap_vld,
        pkt_v_value_3_080_out => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_pkt_v_value_3_080_out,
        pkt_v_value_3_080_out_ap_vld => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_pkt_v_value_3_080_out_ap_vld,
        pkt_v_value_2_079_out => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_pkt_v_value_2_079_out,
        pkt_v_value_2_079_out_ap_vld => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_pkt_v_value_2_079_out_ap_vld,
        pkt_v_value_1_078_out => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_pkt_v_value_1_078_out,
        pkt_v_value_1_078_out_ap_vld => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_pkt_v_value_1_078_out_ap_vld,
        pkt_v_value_0_077_out => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_pkt_v_value_0_077_out,
        pkt_v_value_0_077_out_ap_vld => grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_pkt_v_value_0_077_out_ap_vld);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_ap_ready = ap_const_logic_1)) then 
                    grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_set_tile_broadcast_Pipeline_init_seen_fu_170_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_set_tile_broadcast_Pipeline_init_seen_fu_170_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    grp_set_tile_broadcast_Pipeline_init_seen_fu_170_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_set_tile_broadcast_Pipeline_init_seen_fu_170_ap_ready = ap_const_logic_1)) then 
                    grp_set_tile_broadcast_Pipeline_init_seen_fu_170_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, s_0_full_n, s_1_full_n, s_2_full_n, s_3_full_n, ap_CS_fsm_state5, grp_set_tile_broadcast_Pipeline_init_seen_fu_170_ap_done, grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_ap_done, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_set_tile_broadcast_Pipeline_init_seen_fu_170_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                if ((not(((s_3_full_n = ap_const_logic_0) or (s_2_full_n = ap_const_logic_0) or (s_1_full_n = ap_const_logic_0) or (s_0_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_set_tile_broadcast_Pipeline_init_seen_fu_170_ap_done)
    begin
        if ((grp_set_tile_broadcast_Pipeline_init_seen_fu_170_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_ap_done)
    begin
        if ((grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state5_blk_assign_proc : process(s_0_full_n, s_1_full_n, s_2_full_n, s_3_full_n)
    begin
        if (((s_3_full_n = ap_const_logic_0) or (s_2_full_n = ap_const_logic_0) or (s_1_full_n = ap_const_logic_0) or (s_0_full_n = ap_const_logic_0))) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state5_assign_proc : process(s_0_full_n, s_1_full_n, s_2_full_n, s_3_full_n)
    begin
                ap_block_state5 <= ((s_3_full_n = ap_const_logic_0) or (s_2_full_n = ap_const_logic_0) or (s_1_full_n = ap_const_logic_0) or (s_0_full_n = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, s_0_full_n, s_1_full_n, s_2_full_n, s_3_full_n, ap_CS_fsm_state5)
    begin
        if (((not(((s_3_full_n = ap_const_logic_0) or (s_2_full_n = ap_const_logic_0) or (s_1_full_n = ap_const_logic_0) or (s_0_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state5)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(s_0_full_n, s_1_full_n, s_2_full_n, s_3_full_n, ap_CS_fsm_state5)
    begin
        if ((not(((s_3_full_n = ap_const_logic_0) or (s_2_full_n = ap_const_logic_0) or (s_1_full_n = ap_const_logic_0) or (s_0_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    bitcast_ln96_1_fu_266_p1 <= grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_pkt_v_value_1_078_out;
    bitcast_ln96_2_fu_270_p1 <= grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_pkt_v_value_2_079_out;
    bitcast_ln96_3_fu_274_p1 <= grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_pkt_v_value_3_080_out;
    bitcast_ln96_fu_262_p1 <= grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_pkt_v_value_0_077_out;
    grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_ap_start <= grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_ap_start_reg;
    grp_set_tile_broadcast_Pipeline_init_seen_fu_170_ap_start <= grp_set_tile_broadcast_Pipeline_init_seen_fu_170_ap_start_reg;
    m_axi_gmem1_ARADDR <= grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_ARADDR;
    m_axi_gmem1_ARBURST <= grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_ARBURST;
    m_axi_gmem1_ARCACHE <= grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_ARCACHE;
    m_axi_gmem1_ARID <= grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_ARID;
    m_axi_gmem1_ARLEN <= grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_ARLEN;
    m_axi_gmem1_ARLOCK <= grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_ARLOCK;
    m_axi_gmem1_ARPROT <= grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_ARPROT;
    m_axi_gmem1_ARQOS <= grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_ARQOS;
    m_axi_gmem1_ARREGION <= grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_ARREGION;
    m_axi_gmem1_ARSIZE <= grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_ARSIZE;
    m_axi_gmem1_ARUSER <= grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_ARUSER;

    m_axi_gmem1_ARVALID_assign_proc : process(ap_CS_fsm_state3, grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_ARVALID, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            m_axi_gmem1_ARVALID <= grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_ARVALID;
        else 
            m_axi_gmem1_ARVALID <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem1_AWADDR <= ap_const_lv64_0;
    m_axi_gmem1_AWBURST <= ap_const_lv2_0;
    m_axi_gmem1_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem1_AWID <= ap_const_lv1_0;
    m_axi_gmem1_AWLEN <= ap_const_lv32_0;
    m_axi_gmem1_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem1_AWPROT <= ap_const_lv3_0;
    m_axi_gmem1_AWQOS <= ap_const_lv4_0;
    m_axi_gmem1_AWREGION <= ap_const_lv4_0;
    m_axi_gmem1_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem1_AWUSER <= ap_const_lv1_0;
    m_axi_gmem1_AWVALID <= ap_const_logic_0;
    m_axi_gmem1_BREADY <= ap_const_logic_0;

    m_axi_gmem1_RREADY_assign_proc : process(ap_CS_fsm_state3, grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_RREADY, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            m_axi_gmem1_RREADY <= grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem1_RREADY;
        else 
            m_axi_gmem1_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem1_WDATA <= ap_const_lv32_0;
    m_axi_gmem1_WID <= ap_const_lv1_0;
    m_axi_gmem1_WLAST <= ap_const_logic_0;
    m_axi_gmem1_WSTRB <= ap_const_lv4_0;
    m_axi_gmem1_WUSER <= ap_const_lv1_0;
    m_axi_gmem1_WVALID <= ap_const_logic_0;
    m_axi_gmem2_ARADDR <= grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_ARADDR;
    m_axi_gmem2_ARBURST <= grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_ARBURST;
    m_axi_gmem2_ARCACHE <= grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_ARCACHE;
    m_axi_gmem2_ARID <= grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_ARID;
    m_axi_gmem2_ARLEN <= grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_ARLEN;
    m_axi_gmem2_ARLOCK <= grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_ARLOCK;
    m_axi_gmem2_ARPROT <= grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_ARPROT;
    m_axi_gmem2_ARQOS <= grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_ARQOS;
    m_axi_gmem2_ARREGION <= grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_ARREGION;
    m_axi_gmem2_ARSIZE <= grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_ARSIZE;
    m_axi_gmem2_ARUSER <= grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_ARUSER;

    m_axi_gmem2_ARVALID_assign_proc : process(ap_CS_fsm_state3, grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_ARVALID, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            m_axi_gmem2_ARVALID <= grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_ARVALID;
        else 
            m_axi_gmem2_ARVALID <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem2_AWADDR <= ap_const_lv64_0;
    m_axi_gmem2_AWBURST <= ap_const_lv2_0;
    m_axi_gmem2_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem2_AWID <= ap_const_lv1_0;
    m_axi_gmem2_AWLEN <= ap_const_lv32_0;
    m_axi_gmem2_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem2_AWPROT <= ap_const_lv3_0;
    m_axi_gmem2_AWQOS <= ap_const_lv4_0;
    m_axi_gmem2_AWREGION <= ap_const_lv4_0;
    m_axi_gmem2_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem2_AWUSER <= ap_const_lv1_0;
    m_axi_gmem2_AWVALID <= ap_const_logic_0;
    m_axi_gmem2_BREADY <= ap_const_logic_0;

    m_axi_gmem2_RREADY_assign_proc : process(ap_CS_fsm_state3, grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_RREADY, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            m_axi_gmem2_RREADY <= grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_m_axi_gmem2_RREADY;
        else 
            m_axi_gmem2_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem2_WDATA <= ap_const_lv32_0;
    m_axi_gmem2_WID <= ap_const_lv1_0;
    m_axi_gmem2_WLAST <= ap_const_logic_0;
    m_axi_gmem2_WSTRB <= ap_const_lv4_0;
    m_axi_gmem2_WUSER <= ap_const_lv1_0;
    m_axi_gmem2_WVALID <= ap_const_logic_0;
    p_0_fu_278_p17 <= (((((((((((((((grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_pkt_ref_3_088_out & grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_pkt_ref_2_087_out) & grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_pkt_ref_1_086_out) & grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_pkt_ref_0_085_out) & grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_pkt_v_y_3_084_out) & ap_const_lv32_0) & bitcast_ln96_3_fu_274_p1) & grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_pkt_v_y_2_083_out) & ap_const_lv32_0) & bitcast_ln96_2_fu_270_p1) & grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_pkt_v_y_1_082_out) & ap_const_lv32_0) & bitcast_ln96_1_fu_266_p1) & grp_set_tile_broadcast_Pipeline_copy_tile_loop_fu_178_pkt_v_y_0_081_out) & ap_const_lv32_0) & bitcast_ln96_fu_262_p1);

    s_0_blk_n_assign_proc : process(s_0_full_n, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            s_0_blk_n <= s_0_full_n;
        else 
            s_0_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    s_0_din <= p_0_fu_278_p17;

    s_0_write_assign_proc : process(s_0_full_n, s_1_full_n, s_2_full_n, s_3_full_n, ap_CS_fsm_state5)
    begin
        if ((not(((s_3_full_n = ap_const_logic_0) or (s_2_full_n = ap_const_logic_0) or (s_1_full_n = ap_const_logic_0) or (s_0_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            s_0_write <= ap_const_logic_1;
        else 
            s_0_write <= ap_const_logic_0;
        end if; 
    end process;


    s_1_blk_n_assign_proc : process(s_1_full_n, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            s_1_blk_n <= s_1_full_n;
        else 
            s_1_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    s_1_din <= p_0_fu_278_p17;

    s_1_write_assign_proc : process(s_0_full_n, s_1_full_n, s_2_full_n, s_3_full_n, ap_CS_fsm_state5)
    begin
        if ((not(((s_3_full_n = ap_const_logic_0) or (s_2_full_n = ap_const_logic_0) or (s_1_full_n = ap_const_logic_0) or (s_0_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            s_1_write <= ap_const_logic_1;
        else 
            s_1_write <= ap_const_logic_0;
        end if; 
    end process;


    s_2_blk_n_assign_proc : process(s_2_full_n, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            s_2_blk_n <= s_2_full_n;
        else 
            s_2_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    s_2_din <= p_0_fu_278_p17;

    s_2_write_assign_proc : process(s_0_full_n, s_1_full_n, s_2_full_n, s_3_full_n, ap_CS_fsm_state5)
    begin
        if ((not(((s_3_full_n = ap_const_logic_0) or (s_2_full_n = ap_const_logic_0) or (s_1_full_n = ap_const_logic_0) or (s_0_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            s_2_write <= ap_const_logic_1;
        else 
            s_2_write <= ap_const_logic_0;
        end if; 
    end process;


    s_3_blk_n_assign_proc : process(s_3_full_n, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            s_3_blk_n <= s_3_full_n;
        else 
            s_3_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    s_3_din <= p_0_fu_278_p17;

    s_3_write_assign_proc : process(s_0_full_n, s_1_full_n, s_2_full_n, s_3_full_n, ap_CS_fsm_state5)
    begin
        if ((not(((s_3_full_n = ap_const_logic_0) or (s_2_full_n = ap_const_logic_0) or (s_1_full_n = ap_const_logic_0) or (s_0_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            s_3_write <= ap_const_logic_1;
        else 
            s_3_write <= ap_const_logic_0;
        end if; 
    end process;

end behav;
