// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module spmm_hls_dataflow_in_loop_row_loop (
        m_axi_gmem1_AWVALID,
        m_axi_gmem1_AWREADY,
        m_axi_gmem1_AWADDR,
        m_axi_gmem1_AWID,
        m_axi_gmem1_AWLEN,
        m_axi_gmem1_AWSIZE,
        m_axi_gmem1_AWBURST,
        m_axi_gmem1_AWLOCK,
        m_axi_gmem1_AWCACHE,
        m_axi_gmem1_AWPROT,
        m_axi_gmem1_AWQOS,
        m_axi_gmem1_AWREGION,
        m_axi_gmem1_AWUSER,
        m_axi_gmem1_WVALID,
        m_axi_gmem1_WREADY,
        m_axi_gmem1_WDATA,
        m_axi_gmem1_WSTRB,
        m_axi_gmem1_WLAST,
        m_axi_gmem1_WID,
        m_axi_gmem1_WUSER,
        m_axi_gmem1_ARVALID,
        m_axi_gmem1_ARREADY,
        m_axi_gmem1_ARADDR,
        m_axi_gmem1_ARID,
        m_axi_gmem1_ARLEN,
        m_axi_gmem1_ARSIZE,
        m_axi_gmem1_ARBURST,
        m_axi_gmem1_ARLOCK,
        m_axi_gmem1_ARCACHE,
        m_axi_gmem1_ARPROT,
        m_axi_gmem1_ARQOS,
        m_axi_gmem1_ARREGION,
        m_axi_gmem1_ARUSER,
        m_axi_gmem1_RVALID,
        m_axi_gmem1_RREADY,
        m_axi_gmem1_RDATA,
        m_axi_gmem1_RLAST,
        m_axi_gmem1_RID,
        m_axi_gmem1_RFIFONUM,
        m_axi_gmem1_RUSER,
        m_axi_gmem1_RRESP,
        m_axi_gmem1_BVALID,
        m_axi_gmem1_BREADY,
        m_axi_gmem1_BRESP,
        m_axi_gmem1_BID,
        m_axi_gmem1_BUSER,
        col_idx,
        m_axi_gmem2_AWVALID,
        m_axi_gmem2_AWREADY,
        m_axi_gmem2_AWADDR,
        m_axi_gmem2_AWID,
        m_axi_gmem2_AWLEN,
        m_axi_gmem2_AWSIZE,
        m_axi_gmem2_AWBURST,
        m_axi_gmem2_AWLOCK,
        m_axi_gmem2_AWCACHE,
        m_axi_gmem2_AWPROT,
        m_axi_gmem2_AWQOS,
        m_axi_gmem2_AWREGION,
        m_axi_gmem2_AWUSER,
        m_axi_gmem2_WVALID,
        m_axi_gmem2_WREADY,
        m_axi_gmem2_WDATA,
        m_axi_gmem2_WSTRB,
        m_axi_gmem2_WLAST,
        m_axi_gmem2_WID,
        m_axi_gmem2_WUSER,
        m_axi_gmem2_ARVALID,
        m_axi_gmem2_ARREADY,
        m_axi_gmem2_ARADDR,
        m_axi_gmem2_ARID,
        m_axi_gmem2_ARLEN,
        m_axi_gmem2_ARSIZE,
        m_axi_gmem2_ARBURST,
        m_axi_gmem2_ARLOCK,
        m_axi_gmem2_ARCACHE,
        m_axi_gmem2_ARPROT,
        m_axi_gmem2_ARQOS,
        m_axi_gmem2_ARREGION,
        m_axi_gmem2_ARUSER,
        m_axi_gmem2_RVALID,
        m_axi_gmem2_RREADY,
        m_axi_gmem2_RDATA,
        m_axi_gmem2_RLAST,
        m_axi_gmem2_RID,
        m_axi_gmem2_RFIFONUM,
        m_axi_gmem2_RUSER,
        m_axi_gmem2_RRESP,
        m_axi_gmem2_BVALID,
        m_axi_gmem2_BREADY,
        m_axi_gmem2_BRESP,
        m_axi_gmem2_BID,
        m_axi_gmem2_BUSER,
        a_val,
        i,
        nnz,
        ap_clk,
        ap_rst,
        col_idx_ap_vld,
        a_val_ap_vld,
        i_ap_vld,
        nnz_ap_vld,
        ap_start,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


output   m_axi_gmem1_AWVALID;
input   m_axi_gmem1_AWREADY;
output  [63:0] m_axi_gmem1_AWADDR;
output  [0:0] m_axi_gmem1_AWID;
output  [31:0] m_axi_gmem1_AWLEN;
output  [2:0] m_axi_gmem1_AWSIZE;
output  [1:0] m_axi_gmem1_AWBURST;
output  [1:0] m_axi_gmem1_AWLOCK;
output  [3:0] m_axi_gmem1_AWCACHE;
output  [2:0] m_axi_gmem1_AWPROT;
output  [3:0] m_axi_gmem1_AWQOS;
output  [3:0] m_axi_gmem1_AWREGION;
output  [0:0] m_axi_gmem1_AWUSER;
output   m_axi_gmem1_WVALID;
input   m_axi_gmem1_WREADY;
output  [31:0] m_axi_gmem1_WDATA;
output  [3:0] m_axi_gmem1_WSTRB;
output   m_axi_gmem1_WLAST;
output  [0:0] m_axi_gmem1_WID;
output  [0:0] m_axi_gmem1_WUSER;
output   m_axi_gmem1_ARVALID;
input   m_axi_gmem1_ARREADY;
output  [63:0] m_axi_gmem1_ARADDR;
output  [0:0] m_axi_gmem1_ARID;
output  [31:0] m_axi_gmem1_ARLEN;
output  [2:0] m_axi_gmem1_ARSIZE;
output  [1:0] m_axi_gmem1_ARBURST;
output  [1:0] m_axi_gmem1_ARLOCK;
output  [3:0] m_axi_gmem1_ARCACHE;
output  [2:0] m_axi_gmem1_ARPROT;
output  [3:0] m_axi_gmem1_ARQOS;
output  [3:0] m_axi_gmem1_ARREGION;
output  [0:0] m_axi_gmem1_ARUSER;
input   m_axi_gmem1_RVALID;
output   m_axi_gmem1_RREADY;
input  [31:0] m_axi_gmem1_RDATA;
input   m_axi_gmem1_RLAST;
input  [0:0] m_axi_gmem1_RID;
input  [8:0] m_axi_gmem1_RFIFONUM;
input  [0:0] m_axi_gmem1_RUSER;
input  [1:0] m_axi_gmem1_RRESP;
input   m_axi_gmem1_BVALID;
output   m_axi_gmem1_BREADY;
input  [1:0] m_axi_gmem1_BRESP;
input  [0:0] m_axi_gmem1_BID;
input  [0:0] m_axi_gmem1_BUSER;
input  [63:0] col_idx;
output   m_axi_gmem2_AWVALID;
input   m_axi_gmem2_AWREADY;
output  [63:0] m_axi_gmem2_AWADDR;
output  [0:0] m_axi_gmem2_AWID;
output  [31:0] m_axi_gmem2_AWLEN;
output  [2:0] m_axi_gmem2_AWSIZE;
output  [1:0] m_axi_gmem2_AWBURST;
output  [1:0] m_axi_gmem2_AWLOCK;
output  [3:0] m_axi_gmem2_AWCACHE;
output  [2:0] m_axi_gmem2_AWPROT;
output  [3:0] m_axi_gmem2_AWQOS;
output  [3:0] m_axi_gmem2_AWREGION;
output  [0:0] m_axi_gmem2_AWUSER;
output   m_axi_gmem2_WVALID;
input   m_axi_gmem2_WREADY;
output  [31:0] m_axi_gmem2_WDATA;
output  [3:0] m_axi_gmem2_WSTRB;
output   m_axi_gmem2_WLAST;
output  [0:0] m_axi_gmem2_WID;
output  [0:0] m_axi_gmem2_WUSER;
output   m_axi_gmem2_ARVALID;
input   m_axi_gmem2_ARREADY;
output  [63:0] m_axi_gmem2_ARADDR;
output  [0:0] m_axi_gmem2_ARID;
output  [31:0] m_axi_gmem2_ARLEN;
output  [2:0] m_axi_gmem2_ARSIZE;
output  [1:0] m_axi_gmem2_ARBURST;
output  [1:0] m_axi_gmem2_ARLOCK;
output  [3:0] m_axi_gmem2_ARCACHE;
output  [2:0] m_axi_gmem2_ARPROT;
output  [3:0] m_axi_gmem2_ARQOS;
output  [3:0] m_axi_gmem2_ARREGION;
output  [0:0] m_axi_gmem2_ARUSER;
input   m_axi_gmem2_RVALID;
output   m_axi_gmem2_RREADY;
input  [31:0] m_axi_gmem2_RDATA;
input   m_axi_gmem2_RLAST;
input  [0:0] m_axi_gmem2_RID;
input  [8:0] m_axi_gmem2_RFIFONUM;
input  [0:0] m_axi_gmem2_RUSER;
input  [1:0] m_axi_gmem2_RRESP;
input   m_axi_gmem2_BVALID;
output   m_axi_gmem2_BREADY;
input  [1:0] m_axi_gmem2_BRESP;
input  [0:0] m_axi_gmem2_BID;
input  [0:0] m_axi_gmem2_BUSER;
input  [63:0] a_val;
input  [31:0] i;
input  [31:0] nnz;
input   ap_clk;
input   ap_rst;
input   col_idx_ap_vld;
input   a_val_ap_vld;
input   i_ap_vld;
input   nnz_ap_vld;
input   ap_start;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

wire    set_tile_broadcast_U0_ap_start;
wire    set_tile_broadcast_U0_start_full_n;
wire    set_tile_broadcast_U0_ap_done;
wire    set_tile_broadcast_U0_ap_continue;
wire    set_tile_broadcast_U0_ap_idle;
wire    set_tile_broadcast_U0_ap_ready;
wire    set_tile_broadcast_U0_start_out;
wire    set_tile_broadcast_U0_start_write;
wire    set_tile_broadcast_U0_m_axi_gmem1_AWVALID;
wire   [63:0] set_tile_broadcast_U0_m_axi_gmem1_AWADDR;
wire   [0:0] set_tile_broadcast_U0_m_axi_gmem1_AWID;
wire   [31:0] set_tile_broadcast_U0_m_axi_gmem1_AWLEN;
wire   [2:0] set_tile_broadcast_U0_m_axi_gmem1_AWSIZE;
wire   [1:0] set_tile_broadcast_U0_m_axi_gmem1_AWBURST;
wire   [1:0] set_tile_broadcast_U0_m_axi_gmem1_AWLOCK;
wire   [3:0] set_tile_broadcast_U0_m_axi_gmem1_AWCACHE;
wire   [2:0] set_tile_broadcast_U0_m_axi_gmem1_AWPROT;
wire   [3:0] set_tile_broadcast_U0_m_axi_gmem1_AWQOS;
wire   [3:0] set_tile_broadcast_U0_m_axi_gmem1_AWREGION;
wire   [0:0] set_tile_broadcast_U0_m_axi_gmem1_AWUSER;
wire    set_tile_broadcast_U0_m_axi_gmem1_WVALID;
wire   [31:0] set_tile_broadcast_U0_m_axi_gmem1_WDATA;
wire   [3:0] set_tile_broadcast_U0_m_axi_gmem1_WSTRB;
wire    set_tile_broadcast_U0_m_axi_gmem1_WLAST;
wire   [0:0] set_tile_broadcast_U0_m_axi_gmem1_WID;
wire   [0:0] set_tile_broadcast_U0_m_axi_gmem1_WUSER;
wire    set_tile_broadcast_U0_m_axi_gmem1_ARVALID;
wire   [63:0] set_tile_broadcast_U0_m_axi_gmem1_ARADDR;
wire   [0:0] set_tile_broadcast_U0_m_axi_gmem1_ARID;
wire   [31:0] set_tile_broadcast_U0_m_axi_gmem1_ARLEN;
wire   [2:0] set_tile_broadcast_U0_m_axi_gmem1_ARSIZE;
wire   [1:0] set_tile_broadcast_U0_m_axi_gmem1_ARBURST;
wire   [1:0] set_tile_broadcast_U0_m_axi_gmem1_ARLOCK;
wire   [3:0] set_tile_broadcast_U0_m_axi_gmem1_ARCACHE;
wire   [2:0] set_tile_broadcast_U0_m_axi_gmem1_ARPROT;
wire   [3:0] set_tile_broadcast_U0_m_axi_gmem1_ARQOS;
wire   [3:0] set_tile_broadcast_U0_m_axi_gmem1_ARREGION;
wire   [0:0] set_tile_broadcast_U0_m_axi_gmem1_ARUSER;
wire    set_tile_broadcast_U0_m_axi_gmem1_RREADY;
wire    set_tile_broadcast_U0_m_axi_gmem1_BREADY;
wire    set_tile_broadcast_U0_m_axi_gmem2_AWVALID;
wire   [63:0] set_tile_broadcast_U0_m_axi_gmem2_AWADDR;
wire   [0:0] set_tile_broadcast_U0_m_axi_gmem2_AWID;
wire   [31:0] set_tile_broadcast_U0_m_axi_gmem2_AWLEN;
wire   [2:0] set_tile_broadcast_U0_m_axi_gmem2_AWSIZE;
wire   [1:0] set_tile_broadcast_U0_m_axi_gmem2_AWBURST;
wire   [1:0] set_tile_broadcast_U0_m_axi_gmem2_AWLOCK;
wire   [3:0] set_tile_broadcast_U0_m_axi_gmem2_AWCACHE;
wire   [2:0] set_tile_broadcast_U0_m_axi_gmem2_AWPROT;
wire   [3:0] set_tile_broadcast_U0_m_axi_gmem2_AWQOS;
wire   [3:0] set_tile_broadcast_U0_m_axi_gmem2_AWREGION;
wire   [0:0] set_tile_broadcast_U0_m_axi_gmem2_AWUSER;
wire    set_tile_broadcast_U0_m_axi_gmem2_WVALID;
wire   [31:0] set_tile_broadcast_U0_m_axi_gmem2_WDATA;
wire   [3:0] set_tile_broadcast_U0_m_axi_gmem2_WSTRB;
wire    set_tile_broadcast_U0_m_axi_gmem2_WLAST;
wire   [0:0] set_tile_broadcast_U0_m_axi_gmem2_WID;
wire   [0:0] set_tile_broadcast_U0_m_axi_gmem2_WUSER;
wire    set_tile_broadcast_U0_m_axi_gmem2_ARVALID;
wire   [63:0] set_tile_broadcast_U0_m_axi_gmem2_ARADDR;
wire   [0:0] set_tile_broadcast_U0_m_axi_gmem2_ARID;
wire   [31:0] set_tile_broadcast_U0_m_axi_gmem2_ARLEN;
wire   [2:0] set_tile_broadcast_U0_m_axi_gmem2_ARSIZE;
wire   [1:0] set_tile_broadcast_U0_m_axi_gmem2_ARBURST;
wire   [1:0] set_tile_broadcast_U0_m_axi_gmem2_ARLOCK;
wire   [3:0] set_tile_broadcast_U0_m_axi_gmem2_ARCACHE;
wire   [2:0] set_tile_broadcast_U0_m_axi_gmem2_ARPROT;
wire   [3:0] set_tile_broadcast_U0_m_axi_gmem2_ARQOS;
wire   [3:0] set_tile_broadcast_U0_m_axi_gmem2_ARREGION;
wire   [0:0] set_tile_broadcast_U0_m_axi_gmem2_ARUSER;
wire    set_tile_broadcast_U0_m_axi_gmem2_RREADY;
wire    set_tile_broadcast_U0_m_axi_gmem2_BREADY;
wire   [387:0] set_tile_broadcast_U0_s_0_din;
wire    set_tile_broadcast_U0_s_0_write;
wire   [387:0] set_tile_broadcast_U0_s_1_din;
wire    set_tile_broadcast_U0_s_1_write;
wire   [387:0] set_tile_broadcast_U0_s_2_din;
wire    set_tile_broadcast_U0_s_2_write;
wire   [387:0] set_tile_broadcast_U0_s_3_din;
wire    set_tile_broadcast_U0_s_3_write;
wire    pu_kernel_U0_ap_start;
wire    pu_kernel_U0_ap_done;
wire    pu_kernel_U0_ap_continue;
wire    pu_kernel_U0_ap_idle;
wire    pu_kernel_U0_ap_ready;
wire    pu_kernel_U0_s_0_read;
wire    ap_sync_continue;
wire    pu_kernel_1_U0_ap_start;
wire    pu_kernel_1_U0_ap_done;
wire    pu_kernel_1_U0_ap_continue;
wire    pu_kernel_1_U0_ap_idle;
wire    pu_kernel_1_U0_ap_ready;
wire    pu_kernel_1_U0_s_1_read;
wire    pu_kernel_2_U0_ap_start;
wire    pu_kernel_2_U0_ap_done;
wire    pu_kernel_2_U0_ap_continue;
wire    pu_kernel_2_U0_ap_idle;
wire    pu_kernel_2_U0_ap_ready;
wire    pu_kernel_2_U0_s_2_read;
wire    pu_kernel_3_U0_ap_start;
wire    pu_kernel_3_U0_ap_done;
wire    pu_kernel_3_U0_ap_continue;
wire    pu_kernel_3_U0_ap_idle;
wire    pu_kernel_3_U0_ap_ready;
wire    pu_kernel_3_U0_s_3_read;
wire    s_01_full_n;
wire   [387:0] s_01_dout;
wire   [4:0] s_01_num_data_valid;
wire   [4:0] s_01_fifo_cap;
wire    s_01_empty_n;
wire    s_12_full_n;
wire   [387:0] s_12_dout;
wire   [4:0] s_12_num_data_valid;
wire   [4:0] s_12_fifo_cap;
wire    s_12_empty_n;
wire    s_23_full_n;
wire   [387:0] s_23_dout;
wire   [4:0] s_23_num_data_valid;
wire   [4:0] s_23_fifo_cap;
wire    s_23_empty_n;
wire    s_34_full_n;
wire   [387:0] s_34_dout;
wire   [4:0] s_34_num_data_valid;
wire   [4:0] s_34_fifo_cap;
wire    s_34_empty_n;
wire    ap_sync_done;
wire   [0:0] start_for_pu_kernel_U0_din;
wire    start_for_pu_kernel_U0_full_n;
wire   [0:0] start_for_pu_kernel_U0_dout;
wire    start_for_pu_kernel_U0_empty_n;
wire   [0:0] start_for_pu_kernel_1_U0_din;
wire    start_for_pu_kernel_1_U0_full_n;
wire   [0:0] start_for_pu_kernel_1_U0_dout;
wire    start_for_pu_kernel_1_U0_empty_n;
wire   [0:0] start_for_pu_kernel_2_U0_din;
wire    start_for_pu_kernel_2_U0_full_n;
wire   [0:0] start_for_pu_kernel_2_U0_dout;
wire    start_for_pu_kernel_2_U0_empty_n;
wire   [0:0] start_for_pu_kernel_3_U0_din;
wire    start_for_pu_kernel_3_U0_full_n;
wire   [0:0] start_for_pu_kernel_3_U0_dout;
wire    start_for_pu_kernel_3_U0_empty_n;

spmm_hls_set_tile_broadcast set_tile_broadcast_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(set_tile_broadcast_U0_ap_start),
    .start_full_n(set_tile_broadcast_U0_start_full_n),
    .ap_done(set_tile_broadcast_U0_ap_done),
    .ap_continue(set_tile_broadcast_U0_ap_continue),
    .ap_idle(set_tile_broadcast_U0_ap_idle),
    .ap_ready(set_tile_broadcast_U0_ap_ready),
    .start_out(set_tile_broadcast_U0_start_out),
    .start_write(set_tile_broadcast_U0_start_write),
    .m_axi_gmem1_AWVALID(set_tile_broadcast_U0_m_axi_gmem1_AWVALID),
    .m_axi_gmem1_AWREADY(1'b0),
    .m_axi_gmem1_AWADDR(set_tile_broadcast_U0_m_axi_gmem1_AWADDR),
    .m_axi_gmem1_AWID(set_tile_broadcast_U0_m_axi_gmem1_AWID),
    .m_axi_gmem1_AWLEN(set_tile_broadcast_U0_m_axi_gmem1_AWLEN),
    .m_axi_gmem1_AWSIZE(set_tile_broadcast_U0_m_axi_gmem1_AWSIZE),
    .m_axi_gmem1_AWBURST(set_tile_broadcast_U0_m_axi_gmem1_AWBURST),
    .m_axi_gmem1_AWLOCK(set_tile_broadcast_U0_m_axi_gmem1_AWLOCK),
    .m_axi_gmem1_AWCACHE(set_tile_broadcast_U0_m_axi_gmem1_AWCACHE),
    .m_axi_gmem1_AWPROT(set_tile_broadcast_U0_m_axi_gmem1_AWPROT),
    .m_axi_gmem1_AWQOS(set_tile_broadcast_U0_m_axi_gmem1_AWQOS),
    .m_axi_gmem1_AWREGION(set_tile_broadcast_U0_m_axi_gmem1_AWREGION),
    .m_axi_gmem1_AWUSER(set_tile_broadcast_U0_m_axi_gmem1_AWUSER),
    .m_axi_gmem1_WVALID(set_tile_broadcast_U0_m_axi_gmem1_WVALID),
    .m_axi_gmem1_WREADY(1'b0),
    .m_axi_gmem1_WDATA(set_tile_broadcast_U0_m_axi_gmem1_WDATA),
    .m_axi_gmem1_WSTRB(set_tile_broadcast_U0_m_axi_gmem1_WSTRB),
    .m_axi_gmem1_WLAST(set_tile_broadcast_U0_m_axi_gmem1_WLAST),
    .m_axi_gmem1_WID(set_tile_broadcast_U0_m_axi_gmem1_WID),
    .m_axi_gmem1_WUSER(set_tile_broadcast_U0_m_axi_gmem1_WUSER),
    .m_axi_gmem1_ARVALID(set_tile_broadcast_U0_m_axi_gmem1_ARVALID),
    .m_axi_gmem1_ARREADY(m_axi_gmem1_ARREADY),
    .m_axi_gmem1_ARADDR(set_tile_broadcast_U0_m_axi_gmem1_ARADDR),
    .m_axi_gmem1_ARID(set_tile_broadcast_U0_m_axi_gmem1_ARID),
    .m_axi_gmem1_ARLEN(set_tile_broadcast_U0_m_axi_gmem1_ARLEN),
    .m_axi_gmem1_ARSIZE(set_tile_broadcast_U0_m_axi_gmem1_ARSIZE),
    .m_axi_gmem1_ARBURST(set_tile_broadcast_U0_m_axi_gmem1_ARBURST),
    .m_axi_gmem1_ARLOCK(set_tile_broadcast_U0_m_axi_gmem1_ARLOCK),
    .m_axi_gmem1_ARCACHE(set_tile_broadcast_U0_m_axi_gmem1_ARCACHE),
    .m_axi_gmem1_ARPROT(set_tile_broadcast_U0_m_axi_gmem1_ARPROT),
    .m_axi_gmem1_ARQOS(set_tile_broadcast_U0_m_axi_gmem1_ARQOS),
    .m_axi_gmem1_ARREGION(set_tile_broadcast_U0_m_axi_gmem1_ARREGION),
    .m_axi_gmem1_ARUSER(set_tile_broadcast_U0_m_axi_gmem1_ARUSER),
    .m_axi_gmem1_RVALID(m_axi_gmem1_RVALID),
    .m_axi_gmem1_RREADY(set_tile_broadcast_U0_m_axi_gmem1_RREADY),
    .m_axi_gmem1_RDATA(m_axi_gmem1_RDATA),
    .m_axi_gmem1_RLAST(m_axi_gmem1_RLAST),
    .m_axi_gmem1_RID(m_axi_gmem1_RID),
    .m_axi_gmem1_RFIFONUM(m_axi_gmem1_RFIFONUM),
    .m_axi_gmem1_RUSER(m_axi_gmem1_RUSER),
    .m_axi_gmem1_RRESP(m_axi_gmem1_RRESP),
    .m_axi_gmem1_BVALID(1'b0),
    .m_axi_gmem1_BREADY(set_tile_broadcast_U0_m_axi_gmem1_BREADY),
    .m_axi_gmem1_BRESP(2'd0),
    .m_axi_gmem1_BID(1'd0),
    .m_axi_gmem1_BUSER(1'd0),
    .col_idx(col_idx),
    .m_axi_gmem2_AWVALID(set_tile_broadcast_U0_m_axi_gmem2_AWVALID),
    .m_axi_gmem2_AWREADY(1'b0),
    .m_axi_gmem2_AWADDR(set_tile_broadcast_U0_m_axi_gmem2_AWADDR),
    .m_axi_gmem2_AWID(set_tile_broadcast_U0_m_axi_gmem2_AWID),
    .m_axi_gmem2_AWLEN(set_tile_broadcast_U0_m_axi_gmem2_AWLEN),
    .m_axi_gmem2_AWSIZE(set_tile_broadcast_U0_m_axi_gmem2_AWSIZE),
    .m_axi_gmem2_AWBURST(set_tile_broadcast_U0_m_axi_gmem2_AWBURST),
    .m_axi_gmem2_AWLOCK(set_tile_broadcast_U0_m_axi_gmem2_AWLOCK),
    .m_axi_gmem2_AWCACHE(set_tile_broadcast_U0_m_axi_gmem2_AWCACHE),
    .m_axi_gmem2_AWPROT(set_tile_broadcast_U0_m_axi_gmem2_AWPROT),
    .m_axi_gmem2_AWQOS(set_tile_broadcast_U0_m_axi_gmem2_AWQOS),
    .m_axi_gmem2_AWREGION(set_tile_broadcast_U0_m_axi_gmem2_AWREGION),
    .m_axi_gmem2_AWUSER(set_tile_broadcast_U0_m_axi_gmem2_AWUSER),
    .m_axi_gmem2_WVALID(set_tile_broadcast_U0_m_axi_gmem2_WVALID),
    .m_axi_gmem2_WREADY(1'b0),
    .m_axi_gmem2_WDATA(set_tile_broadcast_U0_m_axi_gmem2_WDATA),
    .m_axi_gmem2_WSTRB(set_tile_broadcast_U0_m_axi_gmem2_WSTRB),
    .m_axi_gmem2_WLAST(set_tile_broadcast_U0_m_axi_gmem2_WLAST),
    .m_axi_gmem2_WID(set_tile_broadcast_U0_m_axi_gmem2_WID),
    .m_axi_gmem2_WUSER(set_tile_broadcast_U0_m_axi_gmem2_WUSER),
    .m_axi_gmem2_ARVALID(set_tile_broadcast_U0_m_axi_gmem2_ARVALID),
    .m_axi_gmem2_ARREADY(m_axi_gmem2_ARREADY),
    .m_axi_gmem2_ARADDR(set_tile_broadcast_U0_m_axi_gmem2_ARADDR),
    .m_axi_gmem2_ARID(set_tile_broadcast_U0_m_axi_gmem2_ARID),
    .m_axi_gmem2_ARLEN(set_tile_broadcast_U0_m_axi_gmem2_ARLEN),
    .m_axi_gmem2_ARSIZE(set_tile_broadcast_U0_m_axi_gmem2_ARSIZE),
    .m_axi_gmem2_ARBURST(set_tile_broadcast_U0_m_axi_gmem2_ARBURST),
    .m_axi_gmem2_ARLOCK(set_tile_broadcast_U0_m_axi_gmem2_ARLOCK),
    .m_axi_gmem2_ARCACHE(set_tile_broadcast_U0_m_axi_gmem2_ARCACHE),
    .m_axi_gmem2_ARPROT(set_tile_broadcast_U0_m_axi_gmem2_ARPROT),
    .m_axi_gmem2_ARQOS(set_tile_broadcast_U0_m_axi_gmem2_ARQOS),
    .m_axi_gmem2_ARREGION(set_tile_broadcast_U0_m_axi_gmem2_ARREGION),
    .m_axi_gmem2_ARUSER(set_tile_broadcast_U0_m_axi_gmem2_ARUSER),
    .m_axi_gmem2_RVALID(m_axi_gmem2_RVALID),
    .m_axi_gmem2_RREADY(set_tile_broadcast_U0_m_axi_gmem2_RREADY),
    .m_axi_gmem2_RDATA(m_axi_gmem2_RDATA),
    .m_axi_gmem2_RLAST(m_axi_gmem2_RLAST),
    .m_axi_gmem2_RID(m_axi_gmem2_RID),
    .m_axi_gmem2_RFIFONUM(m_axi_gmem2_RFIFONUM),
    .m_axi_gmem2_RUSER(m_axi_gmem2_RUSER),
    .m_axi_gmem2_RRESP(m_axi_gmem2_RRESP),
    .m_axi_gmem2_BVALID(1'b0),
    .m_axi_gmem2_BREADY(set_tile_broadcast_U0_m_axi_gmem2_BREADY),
    .m_axi_gmem2_BRESP(2'd0),
    .m_axi_gmem2_BID(1'd0),
    .m_axi_gmem2_BUSER(1'd0),
    .a_val(a_val),
    .s_0_din(set_tile_broadcast_U0_s_0_din),
    .s_0_num_data_valid(s_01_num_data_valid),
    .s_0_fifo_cap(s_01_fifo_cap),
    .s_0_full_n(s_01_full_n),
    .s_0_write(set_tile_broadcast_U0_s_0_write),
    .s_1_din(set_tile_broadcast_U0_s_1_din),
    .s_1_num_data_valid(s_12_num_data_valid),
    .s_1_fifo_cap(s_12_fifo_cap),
    .s_1_full_n(s_12_full_n),
    .s_1_write(set_tile_broadcast_U0_s_1_write),
    .s_2_din(set_tile_broadcast_U0_s_2_din),
    .s_2_num_data_valid(s_23_num_data_valid),
    .s_2_fifo_cap(s_23_fifo_cap),
    .s_2_full_n(s_23_full_n),
    .s_2_write(set_tile_broadcast_U0_s_2_write),
    .s_3_din(set_tile_broadcast_U0_s_3_din),
    .s_3_num_data_valid(s_34_num_data_valid),
    .s_3_fifo_cap(s_34_fifo_cap),
    .s_3_full_n(s_34_full_n),
    .s_3_write(set_tile_broadcast_U0_s_3_write),
    .pointer(i),
    .nnz(nnz)
);

spmm_hls_pu_kernel pu_kernel_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(pu_kernel_U0_ap_start),
    .ap_done(pu_kernel_U0_ap_done),
    .ap_continue(pu_kernel_U0_ap_continue),
    .ap_idle(pu_kernel_U0_ap_idle),
    .ap_ready(pu_kernel_U0_ap_ready),
    .s_0_dout(s_01_dout),
    .s_0_num_data_valid(s_01_num_data_valid),
    .s_0_fifo_cap(s_01_fifo_cap),
    .s_0_empty_n(s_01_empty_n),
    .s_0_read(pu_kernel_U0_s_0_read)
);

spmm_hls_pu_kernel_1 pu_kernel_1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(pu_kernel_1_U0_ap_start),
    .ap_done(pu_kernel_1_U0_ap_done),
    .ap_continue(pu_kernel_1_U0_ap_continue),
    .ap_idle(pu_kernel_1_U0_ap_idle),
    .ap_ready(pu_kernel_1_U0_ap_ready),
    .s_1_dout(s_12_dout),
    .s_1_num_data_valid(s_12_num_data_valid),
    .s_1_fifo_cap(s_12_fifo_cap),
    .s_1_empty_n(s_12_empty_n),
    .s_1_read(pu_kernel_1_U0_s_1_read)
);

spmm_hls_pu_kernel_2 pu_kernel_2_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(pu_kernel_2_U0_ap_start),
    .ap_done(pu_kernel_2_U0_ap_done),
    .ap_continue(pu_kernel_2_U0_ap_continue),
    .ap_idle(pu_kernel_2_U0_ap_idle),
    .ap_ready(pu_kernel_2_U0_ap_ready),
    .s_2_dout(s_23_dout),
    .s_2_num_data_valid(s_23_num_data_valid),
    .s_2_fifo_cap(s_23_fifo_cap),
    .s_2_empty_n(s_23_empty_n),
    .s_2_read(pu_kernel_2_U0_s_2_read)
);

spmm_hls_pu_kernel_3 pu_kernel_3_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(pu_kernel_3_U0_ap_start),
    .ap_done(pu_kernel_3_U0_ap_done),
    .ap_continue(pu_kernel_3_U0_ap_continue),
    .ap_idle(pu_kernel_3_U0_ap_idle),
    .ap_ready(pu_kernel_3_U0_ap_ready),
    .s_3_dout(s_34_dout),
    .s_3_num_data_valid(s_34_num_data_valid),
    .s_3_fifo_cap(s_34_fifo_cap),
    .s_3_empty_n(s_34_empty_n),
    .s_3_read(pu_kernel_3_U0_s_3_read)
);

spmm_hls_fifo_w388_d16_A s_01_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(set_tile_broadcast_U0_s_0_din),
    .if_full_n(s_01_full_n),
    .if_write(set_tile_broadcast_U0_s_0_write),
    .if_dout(s_01_dout),
    .if_num_data_valid(s_01_num_data_valid),
    .if_fifo_cap(s_01_fifo_cap),
    .if_empty_n(s_01_empty_n),
    .if_read(pu_kernel_U0_s_0_read)
);

spmm_hls_fifo_w388_d16_A s_12_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(set_tile_broadcast_U0_s_1_din),
    .if_full_n(s_12_full_n),
    .if_write(set_tile_broadcast_U0_s_1_write),
    .if_dout(s_12_dout),
    .if_num_data_valid(s_12_num_data_valid),
    .if_fifo_cap(s_12_fifo_cap),
    .if_empty_n(s_12_empty_n),
    .if_read(pu_kernel_1_U0_s_1_read)
);

spmm_hls_fifo_w388_d16_A s_23_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(set_tile_broadcast_U0_s_2_din),
    .if_full_n(s_23_full_n),
    .if_write(set_tile_broadcast_U0_s_2_write),
    .if_dout(s_23_dout),
    .if_num_data_valid(s_23_num_data_valid),
    .if_fifo_cap(s_23_fifo_cap),
    .if_empty_n(s_23_empty_n),
    .if_read(pu_kernel_2_U0_s_2_read)
);

spmm_hls_fifo_w388_d16_A s_34_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(set_tile_broadcast_U0_s_3_din),
    .if_full_n(s_34_full_n),
    .if_write(set_tile_broadcast_U0_s_3_write),
    .if_dout(s_34_dout),
    .if_num_data_valid(s_34_num_data_valid),
    .if_fifo_cap(s_34_fifo_cap),
    .if_empty_n(s_34_empty_n),
    .if_read(pu_kernel_3_U0_s_3_read)
);

spmm_hls_start_for_pu_kernel_U0 start_for_pu_kernel_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_pu_kernel_U0_din),
    .if_full_n(start_for_pu_kernel_U0_full_n),
    .if_write(set_tile_broadcast_U0_start_write),
    .if_dout(start_for_pu_kernel_U0_dout),
    .if_empty_n(start_for_pu_kernel_U0_empty_n),
    .if_read(pu_kernel_U0_ap_ready)
);

spmm_hls_start_for_pu_kernel_1_U0 start_for_pu_kernel_1_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_pu_kernel_1_U0_din),
    .if_full_n(start_for_pu_kernel_1_U0_full_n),
    .if_write(set_tile_broadcast_U0_start_write),
    .if_dout(start_for_pu_kernel_1_U0_dout),
    .if_empty_n(start_for_pu_kernel_1_U0_empty_n),
    .if_read(pu_kernel_1_U0_ap_ready)
);

spmm_hls_start_for_pu_kernel_2_U0 start_for_pu_kernel_2_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_pu_kernel_2_U0_din),
    .if_full_n(start_for_pu_kernel_2_U0_full_n),
    .if_write(set_tile_broadcast_U0_start_write),
    .if_dout(start_for_pu_kernel_2_U0_dout),
    .if_empty_n(start_for_pu_kernel_2_U0_empty_n),
    .if_read(pu_kernel_2_U0_ap_ready)
);

spmm_hls_start_for_pu_kernel_3_U0 start_for_pu_kernel_3_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_pu_kernel_3_U0_din),
    .if_full_n(start_for_pu_kernel_3_U0_full_n),
    .if_write(set_tile_broadcast_U0_start_write),
    .if_dout(start_for_pu_kernel_3_U0_dout),
    .if_empty_n(start_for_pu_kernel_3_U0_empty_n),
    .if_read(pu_kernel_3_U0_ap_ready)
);

assign ap_done = ap_sync_done;

assign ap_idle = (set_tile_broadcast_U0_ap_idle & pu_kernel_U0_ap_idle & pu_kernel_3_U0_ap_idle & pu_kernel_2_U0_ap_idle & pu_kernel_1_U0_ap_idle);

assign ap_ready = set_tile_broadcast_U0_ap_ready;

assign ap_sync_continue = (ap_sync_done & ap_continue);

assign ap_sync_done = (pu_kernel_U0_ap_done & pu_kernel_3_U0_ap_done & pu_kernel_2_U0_ap_done & pu_kernel_1_U0_ap_done);

assign m_axi_gmem1_ARADDR = set_tile_broadcast_U0_m_axi_gmem1_ARADDR;

assign m_axi_gmem1_ARBURST = set_tile_broadcast_U0_m_axi_gmem1_ARBURST;

assign m_axi_gmem1_ARCACHE = set_tile_broadcast_U0_m_axi_gmem1_ARCACHE;

assign m_axi_gmem1_ARID = set_tile_broadcast_U0_m_axi_gmem1_ARID;

assign m_axi_gmem1_ARLEN = set_tile_broadcast_U0_m_axi_gmem1_ARLEN;

assign m_axi_gmem1_ARLOCK = set_tile_broadcast_U0_m_axi_gmem1_ARLOCK;

assign m_axi_gmem1_ARPROT = set_tile_broadcast_U0_m_axi_gmem1_ARPROT;

assign m_axi_gmem1_ARQOS = set_tile_broadcast_U0_m_axi_gmem1_ARQOS;

assign m_axi_gmem1_ARREGION = set_tile_broadcast_U0_m_axi_gmem1_ARREGION;

assign m_axi_gmem1_ARSIZE = set_tile_broadcast_U0_m_axi_gmem1_ARSIZE;

assign m_axi_gmem1_ARUSER = set_tile_broadcast_U0_m_axi_gmem1_ARUSER;

assign m_axi_gmem1_ARVALID = set_tile_broadcast_U0_m_axi_gmem1_ARVALID;

assign m_axi_gmem1_AWADDR = 64'd0;

assign m_axi_gmem1_AWBURST = 2'd0;

assign m_axi_gmem1_AWCACHE = 4'd0;

assign m_axi_gmem1_AWID = 1'd0;

assign m_axi_gmem1_AWLEN = 32'd0;

assign m_axi_gmem1_AWLOCK = 2'd0;

assign m_axi_gmem1_AWPROT = 3'd0;

assign m_axi_gmem1_AWQOS = 4'd0;

assign m_axi_gmem1_AWREGION = 4'd0;

assign m_axi_gmem1_AWSIZE = 3'd0;

assign m_axi_gmem1_AWUSER = 1'd0;

assign m_axi_gmem1_AWVALID = 1'b0;

assign m_axi_gmem1_BREADY = 1'b0;

assign m_axi_gmem1_RREADY = set_tile_broadcast_U0_m_axi_gmem1_RREADY;

assign m_axi_gmem1_WDATA = 32'd0;

assign m_axi_gmem1_WID = 1'd0;

assign m_axi_gmem1_WLAST = 1'b0;

assign m_axi_gmem1_WSTRB = 4'd0;

assign m_axi_gmem1_WUSER = 1'd0;

assign m_axi_gmem1_WVALID = 1'b0;

assign m_axi_gmem2_ARADDR = set_tile_broadcast_U0_m_axi_gmem2_ARADDR;

assign m_axi_gmem2_ARBURST = set_tile_broadcast_U0_m_axi_gmem2_ARBURST;

assign m_axi_gmem2_ARCACHE = set_tile_broadcast_U0_m_axi_gmem2_ARCACHE;

assign m_axi_gmem2_ARID = set_tile_broadcast_U0_m_axi_gmem2_ARID;

assign m_axi_gmem2_ARLEN = set_tile_broadcast_U0_m_axi_gmem2_ARLEN;

assign m_axi_gmem2_ARLOCK = set_tile_broadcast_U0_m_axi_gmem2_ARLOCK;

assign m_axi_gmem2_ARPROT = set_tile_broadcast_U0_m_axi_gmem2_ARPROT;

assign m_axi_gmem2_ARQOS = set_tile_broadcast_U0_m_axi_gmem2_ARQOS;

assign m_axi_gmem2_ARREGION = set_tile_broadcast_U0_m_axi_gmem2_ARREGION;

assign m_axi_gmem2_ARSIZE = set_tile_broadcast_U0_m_axi_gmem2_ARSIZE;

assign m_axi_gmem2_ARUSER = set_tile_broadcast_U0_m_axi_gmem2_ARUSER;

assign m_axi_gmem2_ARVALID = set_tile_broadcast_U0_m_axi_gmem2_ARVALID;

assign m_axi_gmem2_AWADDR = 64'd0;

assign m_axi_gmem2_AWBURST = 2'd0;

assign m_axi_gmem2_AWCACHE = 4'd0;

assign m_axi_gmem2_AWID = 1'd0;

assign m_axi_gmem2_AWLEN = 32'd0;

assign m_axi_gmem2_AWLOCK = 2'd0;

assign m_axi_gmem2_AWPROT = 3'd0;

assign m_axi_gmem2_AWQOS = 4'd0;

assign m_axi_gmem2_AWREGION = 4'd0;

assign m_axi_gmem2_AWSIZE = 3'd0;

assign m_axi_gmem2_AWUSER = 1'd0;

assign m_axi_gmem2_AWVALID = 1'b0;

assign m_axi_gmem2_BREADY = 1'b0;

assign m_axi_gmem2_RREADY = set_tile_broadcast_U0_m_axi_gmem2_RREADY;

assign m_axi_gmem2_WDATA = 32'd0;

assign m_axi_gmem2_WID = 1'd0;

assign m_axi_gmem2_WLAST = 1'b0;

assign m_axi_gmem2_WSTRB = 4'd0;

assign m_axi_gmem2_WUSER = 1'd0;

assign m_axi_gmem2_WVALID = 1'b0;

assign pu_kernel_1_U0_ap_continue = ap_sync_continue;

assign pu_kernel_1_U0_ap_start = start_for_pu_kernel_1_U0_empty_n;

assign pu_kernel_2_U0_ap_continue = ap_sync_continue;

assign pu_kernel_2_U0_ap_start = start_for_pu_kernel_2_U0_empty_n;

assign pu_kernel_3_U0_ap_continue = ap_sync_continue;

assign pu_kernel_3_U0_ap_start = start_for_pu_kernel_3_U0_empty_n;

assign pu_kernel_U0_ap_continue = ap_sync_continue;

assign pu_kernel_U0_ap_start = start_for_pu_kernel_U0_empty_n;

assign set_tile_broadcast_U0_ap_continue = 1'b1;

assign set_tile_broadcast_U0_ap_start = ap_start;

assign set_tile_broadcast_U0_start_full_n = (start_for_pu_kernel_U0_full_n & start_for_pu_kernel_3_U0_full_n & start_for_pu_kernel_2_U0_full_n & start_for_pu_kernel_1_U0_full_n);

assign start_for_pu_kernel_1_U0_din = 1'b1;

assign start_for_pu_kernel_2_U0_din = 1'b1;

assign start_for_pu_kernel_3_U0_din = 1'b1;

assign start_for_pu_kernel_U0_din = 1'b1;

endmodule //spmm_hls_dataflow_in_loop_row_loop
